### PR TITLE
WIP: Markdown support using pulldown-cmark

### LINKED ISSUE #73: Support for basic Markdown parsing
Contrary to declaring kak-lsp as the one which can only understand plaintext format, it would be cool if kak-lsp could actually parse markdown and show me some bold and italic text in the info box. I think even a basic support for `**bold** __bold__ *italic* _italic_` would be enough for most documentation.

### PR DESCRIPTION
**Pull request by tadeokondrak**
Fixes #73

To do:
- [ ] Better link formatting
- [ ] Integrate it into other places, not just hover
- [ ] Set the preferred format back to plaintext
- [ ] Use the right name of the crate in the commit message

### CODE REVIEW

**Comment by clad26** [comment]
@tadeokondrak Any update to this???

**Comment by clad26** [comment]
@tadeokondrak Also, will the markdown be scrollable??
Also, if your implementation is complete, can you update this with upstream?

**Comment by tadeokondrak** [comment]
Sorry, I've left this PR untouched for a while. Anyone's free to use the code if they want to continue it, or I might in the future. I'll open a new PR if I update it.

**Comment by clad26** [comment]
@tadeokondrak Did it work for the hover?

**Comment by clad26** [comment]
If it works, can you open the PR?
Like, merge the minimum now, and work on it in the future?

**Pull request closed without merging**
